
import { 
  LayoutDashboard, 
  Users, 
  DoorOpen, 
  Ticket, 
  Stethoscope, 
  Settings
} from 'lucide-react';
import { UserRole, NavItem, Language, Student, EPassDestination } from './types';

export const ROLES_LIST = Object.values(UserRole);

export const NAV_ITEMS: NavItem[] = [
  {
    id: 'dashboard',
    label_en: 'Dashboard',
    label_ar: 'لوحة القيادة',
    icon: LayoutDashboard,
    allowedRoles: Object.values(UserRole)
  },
  {
    id: 'management',
    label_en: 'Management',
    label_ar: 'الإدارة',
    icon: Settings,
    allowedRoles: [UserRole.ADMIN_SGL]
  },
  {
    id: 'attendance',
    label_en: 'Attendance',
    label_ar: 'الحضور',
    icon: Users,
    allowedRoles: [UserRole.TEACHER, UserRole.ADMIN_SGL, UserRole.SUPERVISOR]
  },
  {
    id: 'reception',
    label_en: 'Reception',
    label_ar: 'الاستقبال',
    icon: DoorOpen,
    allowedRoles: [UserRole.ADMIN_SGL, UserRole.SUPERVISOR, UserRole.BUS_SUPERVISOR]
  },
  {
    id: 'epass',
    label_en: 'E-Pass',
    label_ar: 'التصريح الإلكتروني',
    icon: Ticket,
    allowedRoles: [UserRole.TEACHER, UserRole.SUPERVISOR, UserRole.MIDDLE_LEADER, UserRole.ADMIN_SGL]
  },
  {
    id: 'clinic',
    label_en: 'Clinic',
    label_ar: 'العيادة',
    icon: Stethoscope,
    allowedRoles: [UserRole.CLINIC_STAFF, UserRole.ADMIN_SGL]
  }
];

export const EARLY_LEAVE_REASONS = [
  "Medical Appointment",
  "Family Emergency",
  "Sickness",
  "Official Paperwork",
  "Travel",
  "Other"
];

export const PICKUP_RELATIONS = [
  "Father",
  "Mother",
  "Brother",
  "Sister",
  "Driver",
  "Maid",
  "Family Member",
  "Other"
];

export const CLINIC_SYMPTOMS = [
    "Headache",
    "Stomach Ache",
    "Fever",
    "Injury/Cut",
    "Nausea",
    "Dizziness",
    "Cough/Cold",
    "Allergic Reaction",
    "Other"
];

export const CLINIC_OUTCOMES = [
    "ReturnToClass",
    "SentHome"
];

export const DEFAULT_DESTINATIONS: EPassDestination[] = [
    { id: 'Restroom', label_en: 'Restroom', label_ar: 'دورة مياه', iconName: 'Armchair', colorTheme: 'blue', maxDuration: 5 },
    { id: 'Clinic', label_en: 'Clinic', label_ar: 'العيادة', iconName: 'Stethoscope', colorTheme: 'red', maxDuration: 15 },
    { id: 'Library', label_en: 'Library', label_ar: 'المكتبة', iconName: 'Library', colorTheme: 'yellow', maxDuration: 20 },
    { id: 'Office', label_en: 'Admin Office', label_ar: 'الإدارة', iconName: 'Briefcase', colorTheme: 'slate', maxDuration: 10 },
];

export const AVAILABLE_ICONS = [
    'Armchair', 'Stethoscope', 'Library', 'Briefcase', 'Coffee', 'Gamepad2', 'Music', 'Dumbbell', 'Beaker', 'BookOpen', 'Users'
];

export const COLOR_THEMES = [
    { name: 'blue', class: 'bg-blue-50 text-blue-600 hover:bg-blue-100' },
    { name: 'red', class: 'bg-red-50 text-red-600 hover:bg-red-100' },
    { name: 'yellow', class: 'bg-yellow-50 text-yellow-600 hover:bg-yellow-100' },
    { name: 'green', class: 'bg-green-50 text-green-600 hover:bg-green-100' },
    { name: 'purple', class: 'bg-purple-50 text-purple-600 hover:bg-purple-100' },
    { name: 'orange', class: 'bg-orange-50 text-orange-600 hover:bg-orange-100' },
    { name: 'slate', class: 'bg-slate-50 text-slate-600 hover:bg-slate-100' },
];


export const TRANSLATIONS = {
  en: {
    welcome: "Welcome back",
    selectRole: "Select Role to Simulate",
    totalStudents: "Total Students",
    onCampus: "Present on Campus",
    absent: "Absent",
    late: "Late",
    askAi: "Ask AI Analyst",
    aiThinking: "Analyzing Data...",
    recentActivity: "Recent Activity",
    activePasses: "Active E-Passes",
    createPass: "Create E-Pass",
    studentName: "Student Name",
    status: "Status",
    actions: "Actions",
    checkIn: "Check In",
    checkOut: "Check Out",
    lateArrival: "Late Arrival",
    earlyLeave: "Early Leave",
    reason: "Reason",
    transportConflict: "Transport Conflict Alert!",
    busSchedule: "Scheduled for Bus",
    submit: "Submit",
    analyzing: "Analyzing...",
    insight: "AI Insight",
    switchLang: "العربية",
    management: "Management",
    clinic: "Clinic",
    users: "Users",
    students: "Students",
    classes: "Classes",
    upload: "Bulk Upload",
    addUser: "Add User",
    addStudent: "Add Student",
    role: "Role",
    email: "Email",
    grade: "Grade",
    section: "Section",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    studentNumber: "Student No.",
    gender: "Gender",
    male: "Male",
    female: "Female",
    filterBy: "Filter By",
    sortBy: "Sort By",
    searchPlaceholder: "Search by Name or Number...",
    clearFilters: "Clear Filters",
    downloadTemplate: "Download Excel Template",
    pickupBy: "Picked Up By",
    pickupId: "Picker ID Number",
    otherReason: "Specify Reason",
    selectReason: "Select Reason",
    selectRelation: "Select Relation",
    autoAttendance: "Note: Student will be automatically marked as Early Leave (EL) for remaining periods.",
    destinations: "E-Pass Destinations",
    addDestination: "Add Destination",
    editDestination: "Edit Destination",
    duration: "Duration (mins)",
    icon: "Icon",
    color: "Color Theme",
    labelEn: "Label (English)",
    labelAr: "Label (Arabic)",
    // Attendance
    date: "Date",
    period: "Period",
    weekend: "Weekend",
    noAttendance: "No attendance required.",
    selectClass: "Select Class",
    selectClassMsg: "Please select Gender, Grade, and Section to view students.",
    noStudentsFound: "No students found matching these filters.",
    markAllAs: "Mark All As...",
    apply: "Apply",
    clearAll: "Clear All",
    submitChanges: "Submit Changes",
    attendanceSaved: "Attendance Saved",
    confirmClear: "Are you sure you want to clear attendance for visible students?",
    present: "Present",
    excused: "Excused Absent",
    unexcused: "Unexcused",
    // E-Pass
    passes: "Passes",
    passActive: "Pass Active",
    passOverdue: "Pass Overdue",
    endPass: "End Pass",
    return: "Return",
    outOfClass: "OUT WITHOUT PERMISSION",
    studentReturned: "Student Returned",
    dailyLimit: "Daily Limit Reached",
    allowAnyway: "Allow Anyway",
    unauthorized: "UNAUTHORIZED",
    studentOutOfClass: "Student is out of class.",
    selectGender: "Select Gender...",
    selectGrade: "Select Grade...",
    selectSection: "Select Section...",
    activityMonitor: "Activity Monitor",
    issuePass: "Issue Pass",
    totalActive: "Total Active",
    totalOverdue: "Total Overdue",
    destinationBreakdown: "Passes Breakdown",
    activeStudentList: "Active Students List",
    timeElapsed: "Time Elapsed",
    where: "Where",
    // Reception
    readyToProcess: "Ready to Process",
    selectStudentMsg: "Select a student from the list to begin",
    confirmLate: "Confirm Late Arrival",
    confirmLateMsg: "Student will be marked as \"Late\" for the current period.",
    guardianPickup: "Guardian / Pickup",
    pleaseSpecify: "Please specify...",
    transport: "Transport",
    // Management
    timetable: "Timetable",
    timetableConfig: "Timetable Configuration",
    standard: "Standard (Mon-Thu)",
    friday: "Friday (Short Day)",
    sortChrono: "Sort Chronologically",
    startTime: "Start Time",
    endTime: "End Time",
    type: "Type",
    addSlot: "Add Slot",
    saveSchedule: "Save Schedule Changes",
    globalSettings: "Global E-Pass Settings",
    maxPasses: "Max Passes Per Student / Day",
    updateLimit: "Update Limit",
    logout: "Logout",
    generateId: "Generate ID Card",
    printCard: "Print Card",
    academicYear: "Academic Year 2024-2025",
    trackivaAcademy: "Trackiva Academy",
    allGrades: "All Grades",
    allSections: "All Sections",
    allGenders: "All Genders",
    bus: "Bus",
    car: "Car",
    walker: "Walker",
    accessControl: "Access Control",
    manageRoles: "Manage Role Permissions",
    module: "Module",
    access: "Access",
    notifications: "Notifications",
    telegramSettings: "Telegram Configuration",
    securityAlerts: "Security & E-Pass Alerts",
    receptionAlerts: "Reception & Early Leave Alerts",
    botToken: "Bot Token",
    chatId: "Chat ID",
    saveCredentials: "Save Credentials",
    watchlist: "Targeted / Watchlist Student",
    watchlistAlerts: "Targeted Student Alerts",
    watchlistDesc: "Dedicated notifications for students marked as 'Targeted/Watchlisted'.",
    notificationRules: "E-Pass Notification Rules",
    enableNotificationsFor: "Enable Notifications For:",
    // Parent Notification
    parentNotifications: "Parent Notifications",
    parentNotificationsDesc: "Configure Telegram alerts for specific students to notify parents directly.",
    searchStudent: "Search Student...",
    configureParentRules: "Configure Parent Rules",
    parentChatId: "Parent Telegram Chat ID",
    selectEvents: "Select Events to Notify Parent",
    saveParentSettings: "Save Parent Settings",
    // Clinic
    incomingPatients: "Incoming Students",
    noIncoming: "No students currently en route.",
    admitPatient: "Admit Student",
    admitWalkIn: "Admit Walk-in Student",
    logVisit: "Log Visit",
    symptom: "Symptom",
    diagnosis: "Diagnosis / Observations",
    treatment: "Treatment / Medicine",
    notes: "Nurse Notes",
    severity: "Severity",
    outcome: "Outcome",
    emergencyAlert: "EMERGENCY ALERT",
    emergencyConfirm: "Are you sure you want to trigger the Emergency Alert?",
    emergencyConfirmDesc: "This will instantly notify administration and security personnel. Only use for critical situations.",
    visitLogged: "Visit Logged Successfully",
    epidemicWarning: "Epidemic Warning",
    epidemicMsg: "High number of similar cases detected recently:",
    todayVisits: "Today's Visits",
    sentHome: "Sent Home",
    medicalHistory: "Medical History",
    low: "Low",
    medium: "Medium",
    high: "High",
    emergency: "Critical",
    returnToClass: "Return to Class",
    sentHomeAction: "Send Home",
    hospital: "Refer to Hospital",
    analytics: "Analytics",
    commonComplaints: "Common Complaints",
    visitTimeline: "Visit Timeline",
    confirmAction: "Confirm",
    visitsByGrade: "Visits by Grade",
    visitsBySection: "Visits by Section",
    visitsByGender: "Visits by Gender",
    admitted: "Admitted",
    discharged: "Discharged",
    studentReport: "Student Report",
    searchReportPlaceholder: "Search Student Name or ID...",
    totalVisits: "Total Visits",
    selectStudentForReport: "Search and select a student to view their medical report.",
    noVisitsFound: "No visits found for this student.",
  },
  ar: {
    welcome: "مرحباً بعودتك",
    selectRole: "اختر دوراً للمحاكاة",
    totalStudents: "إجمالي الطلاب",
    onCampus: "في الحرم المدرسي",
    absent: "غائب",
    late: "تأخير",
    askAi: "اسأل المحلل الذكي",
    aiThinking: "جاري تحليل البيانات...",
    recentActivity: "النشاط الأخير",
    activePasses: "التصاريح النشطة",
    createPass: "إنشاء تصريح",
    studentName: "اسم الطالب",
    status: "الحالة",
    actions: "إجراءات",
    checkIn: "تسجيل دخول",
    checkOut: "تسجيل خروج",
    lateArrival: "وصول متأخر",
    earlyLeave: "انصراف مبكر",
    reason: "السبب",
    transportConflict: "تنبيه تعارض المواصلات!",
    busSchedule: "مجدول للحافلة",
    submit: "إرسال",
    analyzing: "جاري التحليل...",
    insight: "رؤية ذكية",
    switchLang: "English",
    management: "الإدارة",
    clinic: "العيادة",
    users: "المستخدمين",
    students: "الطلاب",
    classes: "الفصول",
    upload: "تحميل جماعي",
    addUser: "إضافة مستخدم",
    addStudent: "إضافة طالب",
    role: "الدور",
    email: "البريد الإلكتروني",
    grade: "الصف",
    section: "الشعبة",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    studentNumber: "رقم الطالب",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    filterBy: "تصفية حسب",
    sortBy: "فرز حسب",
    searchPlaceholder: "بحث بالاسم أو الرقم...",
    clearFilters: "مسح المرشحات",
    downloadTemplate: "تحميل قالب إكسل",
    pickupBy: "تم الاستلام بواسطة",
    pickupId: "رقم هوية المستلم",
    otherReason: "حدد السبب",
    selectReason: "اختر السبب",
    selectRelation: "اختر صلة القرابة",
    autoAttendance: "ملاحظة: سيتم تسجيل الطالب تلقائياً كـ انصراف مبكر (EL) للحصص المتبقية.",
    destinations: "وجهات التصريح",
    addDestination: "إضافة وجهة",
    editDestination: "تعديل الوجهة",
    duration: "المدة (دقائق)",
    icon: "الأيقونة",
    color: "اللون",
    labelEn: "الاسم (إنجليزي)",
    labelAr: "الاسم (عربي)",
    // Attendance
    date: "التاريخ",
    period: "الحصة",
    weekend: "عطلة نهاية الأسبوع",
    noAttendance: "لا يوجد حضور مطلوب.",
    selectClass: "اختر الفصل",
    selectClassMsg: "يرجى اختيار الجنس، الصف، والشعبة لعرض الطلاب.",
    noStudentsFound: "لم يتم العثور على طلاب مطابقين.",
    markAllAs: "تحديد الكل كـ...",
    apply: "تطبيق",
    clearAll: "مسح الكل",
    submitChanges: "إرسال التغييرات",
    attendanceSaved: "تم حفظ الحضور",
    confirmClear: "هل أنت متأكد من مسح الحضور للطلاب الظاهرين؟",
    present: "حاضر",
    excused: "غياب بعذر",
    unexcused: "بدون عذر",
    // E-Pass
    passes: "التصاريح",
    passActive: "تصريح نشط",
    passOverdue: "تصريح متأخر",
    endPass: "إنهاء التصريح",
    return: "عودة",
    outOfClass: "خروج بدون إذن",
    studentReturned: "عاد الطالب",
    dailyLimit: "وصل للحد اليومي",
    allowAnyway: "السماح وتجاوز الحد",
    unauthorized: "غير مصرح",
    studentOutOfClass: "الطالب خارج الفصل.",
    selectGender: "اختر الجنس...",
    selectGrade: "اختر الصف...",
    selectSection: "اختر الشعبة...",
    activityMonitor: "مراقب النشاط",
    issuePass: "إصدار تصريح",
    totalActive: "إجمالي النشطة",
    totalOverdue: "إجمالي المتأخرة",
    destinationBreakdown: "تفاصيل التصاريح",
    activeStudentList: "قائمة الطلاب النشطين",
    timeElapsed: "المدة المنقضية",
    where: "الوجهة",
    // Reception
    readyToProcess: "جاهز للمعالجة",
    selectStudentMsg: "اختر طالباً من القائمة للبدء",
    confirmLate: "تأكيد التأخير",
    confirmLateMsg: "سيتم تسجيل الطالب كـ \"متأخر\" للحصة الحالية.",
    guardianPickup: "ولي الأمر / المستلم",
    pleaseSpecify: "يرجى التحديد...",
    transport: "المواصلات",
    // Management
    timetable: "الجدول الدراسي",
    timetableConfig: "إعدادات الجدول",
    standard: "قياسي (الاثنين-الخميس)",
    friday: "الجمعة (يوم قصير)",
    sortChrono: "فرز زمني",
    startTime: "وقت البدء",
    endTime: "وقت الانتهاء",
    type: "النوع",
    addSlot: "إضافة فترة",
    saveSchedule: "حفظ التغييرات",
    globalSettings: "إعدادات التصريح",
    maxPasses: "الحد الأقصى للتصاريح / يوم",
    updateLimit: "تحديث الحد",
    logout: "تسجيل خروج",
    generateId: "إنشاء بطاقة هوية",
    printCard: "طباعة البطاقة",
    academicYear: "العام الدراسي 2024-2025",
    trackivaAcademy: "أكاديمية تراكيفا",
    allGrades: "كل الصفوف",
    allSections: "كل الشعب",
    allGenders: "كل الأجناس",
    bus: "حافلة",
    car: "سيارة",
    walker: "مشي",
    accessControl: "التحكم في الوصول",
    manageRoles: "إدارة صلاحيات الأدوار",
    module: "الوحدة",
    access: "الوصول",
    notifications: "الإشعارات",
    telegramSettings: "إعدادات تيليجرام",
    securityAlerts: "تنبيهات الأمن والتصاريح",
    receptionAlerts: "تنبيهات الاستقبال والمغادرة",
    botToken: "رمز البوت (Bot Token)",
    chatId: "معرف المحادثة (Chat ID)",
    saveCredentials: "حفظ البيانات",
    watchlist: "طالب مستهدف / قائمة المراقبة",
    watchlistAlerts: "تنبيهات الطلاب المستهدفين",
    watchlistDesc: "إشعارات مخصصة للطلاب المحدد لهم 'مراقبة/استهداف'.",
    notificationRules: "قواعد إشعارات التصريح الإلكتروني",
    enableNotificationsFor: "تفعيل الإشعارات لـ:",
    // Parent Notifications
    parentNotifications: "تنبيهات أولياء الأمور",
    parentNotificationsDesc: "تكوين تنبيهات تيليجرام لطلاب محددين لإخطار أولياء الأمور مباشرة.",
    searchStudent: "بحث عن طالب...",
    configureParentRules: "إعدادات تنبيهات الوالدين",
    parentChatId: "معرف محادثة الوالدين (Chat ID)",
    selectEvents: "اختر الأحداث لتنبيه الوالدين",
    saveParentSettings: "حفظ إعدادات الوالدين",
    // Clinic
    incomingPatients: "الطلاب القادمون",
    noIncoming: "لا يوجد طلاب قادمون حالياً.",
    admitPatient: "استقبال الطالب",
    admitWalkIn: "استقبال طالب (بدون تصريح)",
    logVisit: "تسجيل زيارة",
    symptom: "العرض",
    diagnosis: "التشخيص / الملاحظات",
    treatment: "العلاج / الدواء",
    notes: "ملاحظات الممرض/ة",
    severity: "الحدة",
    outcome: "النتيجة",
    emergencyAlert: "تنبيه طوارئ",
    emergencyConfirm: "هل أنت متأكد من تفعيل تنبيه الطوارئ؟",
    emergencyConfirmDesc: "سيتم إشعار الإدارة وفريق الأمن فوراً. استخدمه فقط في الحالات الحرجة.",
    visitLogged: "تم تسجيل الزيارة بنجاح",
    epidemicWarning: "تحذير وبائي",
    epidemicMsg: "تم رصد عدد كبير من الحالات المتشابهة مؤخراً:",
    todayVisits: "زيارات اليوم",
    sentHome: "تم إرسالهم للمنزل",
    medicalHistory: "السجل الطبي",
    low: "منخفض",
    medium: "متوسط",
    high: "عالي",
    emergency: "حرج",
    returnToClass: "عودة للفصل",
    sentHomeAction: "إرسال للمنزل",
    hospital: "تحويل للمستشفى",
    analytics: "التحليلات",
    commonComplaints: "الشكاوى الشائعة",
    visitTimeline: "الجدول الزمني للزيارات",
    confirmAction: "تأكيد",
    visitsByGrade: "الزيارات حسب الصف",
    visitsBySection: "الزيارات حسب الشعبة",
    visitsByGender: "الزيارات حسب الجنس",
    admitted: "دخول",
    discharged: "خروج",
    studentReport: "تقرير الطالب",
    searchReportPlaceholder: "بحث عن طالب بالاسم أو الرقم...",
    totalVisits: "إجمالي الزيارات",
    selectStudentForReport: "ابحث واختر طالباً لعرض سجله الطبي.",
    noVisitsFound: "لا توجد زيارات مسجلة لهذا الطالب.",
  }
};

// Mock Data Seeds
export const MOCK_STUDENTS: Student[] = [
  { id: 'S001', studentNumber: '2024001', name_en: 'Ahmed Ali', name_ar: 'أحمد علي', gender: 'Male', grade: '10', section: 'A', transportMode: 'Bus', busRoute: 'R-101', isWatchlisted: true },
  { id: 'S002', studentNumber: '2024002', name_en: 'Sarah Smith', name_ar: 'سارة سميث', gender: 'Female', grade: '10', section: 'A', transportMode: 'Car' },
  { id: 'S003', studentNumber: '2024003', name_en: 'John Doe', name_ar: 'جون دو', gender: 'Male', grade: '10', section: 'B', transportMode: 'Walker' },
  { id: 'S004', studentNumber: '2024004', name_en: 'Fatima Noor', name_ar: 'فاطمة نور', gender: 'Female', grade: '11', section: 'A', transportMode: 'Bus', busRoute: 'R-102' },
  { id: 'S005', studentNumber: '2024005', name_en: 'Omar Hassan', name_ar: 'عمر حسن', gender: 'Male', grade: '11', section: 'B', transportMode: 'Car' },
];

export const MOCK_USERS_SEED = [
  { id: 'U001', name: 'Admin User', email: 'admin@trackiva.com', role: UserRole.ADMIN_SGL },
  { id: 'U002', name: 'Sarah Teacher', email: 'sarah@trackiva.com', role: UserRole.TEACHER },
  { id: 'U003', name: 'Mike Supervisor', email: 'mike@trackiva.com', role: UserRole.SUPERVISOR },
];
