
import { 
  LayoutDashboard, 
  Users, 
  DoorOpen, 
  Ticket, 
  Stethoscope, 
  Settings,
  BarChart3
} from 'lucide-react';
import { UserRole, NavItem, EPassDestination } from './types';

export const ROLES_LIST = Object.values(UserRole);

export const NAV_ITEMS: NavItem[] = [
  {
    id: 'dashboard',
    label_en: 'Dashboard',
    label_ar: 'لوحة القيادة',
    icon: LayoutDashboard,
    allowedRoles: Object.values(UserRole)
  },
  {
    id: 'reports',
    label_en: 'Reports',
    label_ar: 'التقارير',
    icon: BarChart3,
    allowedRoles: [UserRole.ADMIN_SGL, UserRole.MIDDLE_LEADER]
  },
  {
    id: 'management',
    label_en: 'Management',
    label_ar: 'الإدارة',
    icon: Settings,
    allowedRoles: [UserRole.ADMIN_SGL]
  },
  {
    id: 'attendance',
    label_en: 'Attendance',
    label_ar: 'الحضور',
    icon: Users,
    allowedRoles: [UserRole.TEACHER, UserRole.ADMIN_SGL, UserRole.SUPERVISOR]
  },
  {
    id: 'reception',
    label_en: 'Reception',
    label_ar: 'الاستقبال',
    icon: DoorOpen,
    allowedRoles: [UserRole.ADMIN_SGL, UserRole.SUPERVISOR, UserRole.BUS_SUPERVISOR]
  },
  {
    id: 'epass',
    label_en: 'E-Pass',
    label_ar: 'التصريح الإلكتروني',
    icon: Ticket,
    allowedRoles: [UserRole.TEACHER, UserRole.SUPERVISOR, UserRole.MIDDLE_LEADER, UserRole.ADMIN_SGL]
  },
  {
    id: 'clinic',
    label_en: 'Clinic',
    label_ar: 'العيادة',
    icon: Stethoscope,
    allowedRoles: [UserRole.CLINIC_STAFF, UserRole.ADMIN_SGL]
  }
];

export const EARLY_LEAVE_REASONS = [
  "Medical Appointment",
  "Family Emergency",
  "Sickness",
  "Official Paperwork",
  "Travel",
  "Other"
];

export const PICKUP_RELATIONS = [
  "Father",
  "Mother",
  "Brother",
  "Sister",
  "Driver",
  "Maid",
  "Family Member",
  "Other"
];

export const CLINIC_SYMPTOMS = [
    "Headache",
    "Stomach Ache",
    "Fever",
    "Injury/Cut",
    "Nausea",
    "Dizziness",
    "Cough/Cold",
    "Allergic Reaction",
    "Other"
];

export const CLINIC_OUTCOMES = [
    "ReturnToClass",
    "SentHome"
];

export const DEFAULT_DESTINATIONS: EPassDestination[] = [
    { id: 'Restroom', label_en: 'Restroom', label_ar: 'دورة مياه', iconName: 'Armchair', colorTheme: 'blue', maxDuration: 5 },
    { id: 'Clinic', label_en: 'Clinic', label_ar: 'العيادة', iconName: 'Stethoscope', colorTheme: 'red', maxDuration: 15 },
    { id: 'Library', label_en: 'Library', label_ar: 'المكتبة', iconName: 'Library', colorTheme: 'yellow', maxDuration: 20 },
    { id: 'Office', label_en: 'Admin Office', label_ar: 'الإدارة', iconName: 'Briefcase', colorTheme: 'slate', maxDuration: 10 },
];

export const AVAILABLE_ICONS = [
    'Armchair', 'Stethoscope', 'Library', 'Briefcase', 'Coffee', 'Gamepad2', 'Music', 'Dumbbell', 'Beaker', 'BookOpen', 'Users'
];

export const COLOR_THEMES = [
    { name: 'blue', class: 'bg-blue-50 text-blue-600 hover:bg-blue-100' },
    { name: 'red', class: 'bg-red-50 text-red-600 hover:bg-red-100' },
    { name: 'yellow', class: 'bg-yellow-50 text-yellow-600 hover:bg-yellow-100' },
    { name: 'green', class: 'bg-green-50 text-green-600 hover:bg-green-100' },
    { name: 'purple', class: 'bg-purple-50 text-purple-600 hover:bg-purple-100' },
    { name: 'orange', class: 'bg-orange-50 text-orange-600 hover:bg-orange-100' },
    { name: 'slate', class: 'bg-slate-50 text-slate-600 hover:bg-slate-100' },
];

export const generateDefaultPermissions = () => {
    const permissions: Record<string, string[]> = {};
    Object.values(UserRole).forEach(role => {
        permissions[role] = NAV_ITEMS.filter(item => item.allowedRoles.includes(role)).map(item => item.id);
    });
    return permissions;
};


export const TRANSLATIONS = {
  en: {
    login: "Login",
    password: "Password",
    demoMode: "Demo Mode",
    signIn: "Sign In",
    loginDescription: "Enter your credentials to access the system.",
    invalidCredentials: "Invalid email or password.",
    welcome: "Welcome back",
    selectRole: "Select Role to Simulate",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    backToLogin: "Back to Login",
    resetLinkSent: "Reset link sent! Check your email.",
    enterEmailToReset: "Enter your email to receive a password reset link.",
    sendLink: "Send Reset Link",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    totalStudents: "Total Students",
    onCampus: "Present on Campus",
    absent: "Absent",
    late: "Late",
    askAi: "Ask AI Analyst",
    aiThinking: "Analyzing Data...",
    recentActivity: "Recent Activity",
    activePasses: "Active E-Passes",
    createPass: "Create E-Pass",
    studentName: "Student Name",
    status: "Status",
    actions: "Actions",
    checkIn: "Check In",
    checkOut: "Check Out",
    lateArrival: "Late Arrival",
    earlyLeave: "Early Leave",
    reason: "Reason",
    transportConflict: "Transport Conflict Alert!",
    busSchedule: "Scheduled for Bus",
    submit: "Submit",
    analyzing: "Analyzing...",
    insight: "AI Insight",
    switchLang: "العربية",
    management: "Management",
    clinic: "Clinic",
    reception: "Reception",
    users: "Users",
    students: "Students",
    classes: "Classes",
    upload: "Upload Students List",
    uploading: "Uploading...",
    addUser: "Add User",
    addStudent: "Add Student",
    role: "Role",
    email: "Email",
    grade: "Grade",
    section: "Section",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    studentNumber: "Student No.",
    gender: "Gender",
    male: "Male",
    female: "Female",
    filterBy: "Filter By",
    sortBy: "Sort By",
    searchPlaceholder: "Search by Name or Number...",
    clearFilters: "Clear Filters",
    downloadTemplate: "Download Excel Template",
    pickupBy: "Picked Up By",
    pickupId: "Picker ID Number",
    otherReason: "Specify Reason",
    selectReason: "Select Reason",
    selectRelation: "Select Relation",
    autoAttendance: "Note: Student will be automatically marked as Early Leave (EL) for remaining periods.",
    destinations: "E-Pass Destinations",
    addDestination: "Add Destination",
    editDestination: "Edit Destination",
    duration: "Duration (mins)",
    icon: "Icon",
    color: "Color Theme",
    labelEn: "Label (English)",
    labelAr: "Label (Arabic)",
    familyId: "Family ID (Sibling Link)",
    siblings: "Siblings Detected",
    // Attendance
    date: "Date",
    period: "Period",
    weekend: "Weekend",
    noAttendance: "No attendance required.",
    selectClass: "Select Class",
    selectClassMsg: "Please select Gender, Grade, and Section to view students.",
    noStudentsFound: "No students found matching these filters.",
    markAllAs: "Mark All As...",
    apply: "Apply",
    clearAll: "Clear All",
    submitChanges: "Submit Changes",
    attendanceSaved: "Attendance Saved",
    confirmClear: "Are you sure you want to clear attendance for visible students?",
    present: "Present",
    excused: "Excused Absent",
    unexcused: "Unexcused",
    enterReason: "Enter Reason for Absence",
    saveReason: "Save Reason",
    // E-Pass
    passes: "Passes",
    passActive: "Pass Active",
    passOverdue: "Pass Overdue",
    endPass: "End Pass",
    return: "Return",
    outOfClass: "OUT WITHOUT PERMISSION",
    studentReturned: "Student Returned",
    dailyLimit: "Daily Limit Reached",
    allowAnyway: "Allow Anyway",
    unauthorized: "UNAUTHORIZED",
    studentOutOfClass: "Student is out of class.",
    selectGender: "Select Gender...",
    selectGrade: "Select Grade...",
    selectSection: "Select Section...",
    activityMonitor: "Activity Monitor",
    issuePass: "Issue Pass",
    totalActive: "Total Active",
    totalOverdue: "Total Overdue",
    destinationBreakdown: "Passes Breakdown",
    activeStudentList: "Active Students List",
    timeElapsed: "Time Elapsed",
    where: "Where",
    issuedBy: "Issued By",
    // Reception
    readyToProcess: "Ready to Process",
    selectStudentMsg: "Select a student from the list to begin",
    confirmLate: "Confirm Late Arrival",
    confirmLateMsg: "Student will be marked as \"Late\" for the current period.",
    guardianPickup: "Guardian / Pickup",
    pleaseSpecify: "Please specify...",
    transport: "Transport",
    // Management
    timetable: "Timetable",
    timetableConfig: "Timetable Configuration",
    standard: "Standard (Mon-Thu)",
    friday: "Friday (Short Day)",
    sortChrono: "Sort Chronologically",
    startTime: "Start Time",
    endTime: "End Time",
    type: "Type",
    addSlot: "Add Slot",
    saveSchedule: "Save Schedule Changes",
    globalSettings: "Global E-Pass Settings",
    maxPasses: "Max Passes Per Student / Day",
    updateLimit: "Update Limit",
    logout: "Logout",
    generateId: "Generate ID Card",
    printCard: "Print Card",
    academicYear: "Academic Year 2024-2025",
    trackivaAcademy: "Trackiva Academy",
    allGrades: "All Grades",
    allSections: "All Sections",
    allGenders: "All Genders",
    bus: "Bus",
    car: "Car",
    walker: "Walker",
    accessControl: "Access Control",
    manageRoles: "Manage Role Permissions",
    module: "Module",
    access: "Access",
    notifications: "Notifications",
    telegramSettings: "Telegram Configuration",
    securityAlerts: "Security & E-Pass Alerts",
    receptionAlerts: "Reception & Early Leave Alerts",
    attendanceAlerts: "Attendance Alerts (Social Worker)",
    botToken: "Bot Token",
    chatId: "Chat ID",
    userChatId: "User Telegram Chat ID",
    saveCredentials: "Save Credentials",
    watchlist: "Targeted / Watchlist Student",
    watchlistAlerts: "Targeted Student Alerts",
    watchlistDesc: "Dedicated notifications for students marked as 'Targeted/Watchlisted'.",
    notificationRules: "E-Pass Notification Rules",
    enableNotificationsFor: "Enable Notifications For:",
    // Parent Notification
    parentNotifications: "Parent Notifications",
    parentNotificationsDesc: "Configure Telegram alerts for specific students to notify parents directly.",
    searchStudent: "Search Student...",
    configureParentRules: "Configure Parent Rules",
    parentChatId: "Parent Telegram Chat ID",
    selectEvents: "Select Events to Notify Parent",
    saveParentSettings: "Save Parent Settings",
    // Attendance Rules
    attendanceRules: "Attendance Rules",
    attendanceRulesDesc: "Configure how daily attendance status is calculated from period records.",
    absentThreshold: "Absent Day Threshold (Periods)",
    absentThresholdDesc: "Number of unexcused absences (periods) to count as a full Absent Day.",
    countAllExcused: "Excused Absence Logic",
    countAllExcusedDesc: "If checked, a student with ALL periods marked 'Excused' will be counted as 'Excused Absent' for the day.",
    attendanceAlertThresholds: "Absence Alert Thresholds (Days)",
    attendanceAlertDesc: "Select which days of accumulated absence trigger a notification to the assigned Social Worker.",
    saveRules: "Save Rules",
    // User Management
    assignedClasses: "Assigned Classes",
    assignClass: "Assign Class",
    selectGradeAndSection: "Select Grade and Section",
    addClass: "Add Class",
    // Clinic
    incomingPatients: "Incoming Students",
    noIncoming: "No students currently en route.",
    admitPatient: "Admit Student",
    admitWalkIn: "Admit Walk-in Student",
    logVisit: "Log Visit",
    symptom: "Symptom",
    diagnosis: "Diagnosis / Observations",
    treatment: "Treatment / Medicine",
    notes: "Nurse Notes",
    severity: "Severity",
    outcome: "Outcome",
    emergencyAlert: "EMERGENCY ALERT",
    emergencyConfirm: "Are you sure you want to trigger the Emergency Alert?",
    emergencyConfirmDesc: "This will instantly notify administration and security personnel. Only use for critical situations.",
    visitLogged: "Visit Logged Successfully",
    epidemicWarning: "Epidemic Warning",
    epidemicMsg: "High number of similar cases detected recently:",
    todayVisits: "Today's Visits",
    sentHome: "Sent Home",
    medicalHistory: "Medical History",
    low: "Low",
    medium: "Medium",
    high: "High",
    emergency: "Critical",
    returnToClass: "Return to Class",
    sentHomeAction: "Send Home",
    hospital: "Refer to Hospital",
    analytics: "Analytics",
    commonComplaints: "Common Complaints",
    visitTimeline: "Visit Timeline",
    confirmAction: "Confirm",
    visitsByGrade: "Visits by Grade",
    visitsBySection: "Visits by Section",
    visitsByGender: "Visits by Gender",
    admitted: "Admitted",
    discharged: "Discharged",
    studentReport: "Student Report",
    searchReportPlaceholder: "Search Student Name or ID...",
    totalVisits: "Total Visits",
    selectStudentForReport: "Search and select a student to view their medical report.",
    noVisitsFound: "No visits found for this student.",
    // Reports
    reports: "Reports",
    dailySummary: "Daily Summary",
    attendanceReport: "Attendance Report",
    clinicReport: "Clinic Report",
    epassReport: "E-Pass Report",
    receptionReport: "Reception Report",
    student360: "Student 360",
    exportReport: "Export Report",
    dateRange: "Date Range",
    startDate: "Start Date",
    endDate: "End Date",
    generate: "Generate",
    cycle: "Cycle",
    cycle1: "Cycle 1 (KG-G4)",
    cycle2: "Cycle 2 (G5-G8)",
    cycle3: "Cycle 3 (G9-G12)",
    absenteeList: "Absentee List",
    absentBuckets: "Absence Frequency",
    bucket1_2: "1-2 days",
    bucket3_5: "3-5 days",
    bucket6_9: "6-9 days",
    bucket10_14: "10-14 days",
    bucket15plus: "15+ days (Flagged)",
    topComplaints: "Top Complaints",
    topEPassUsers: "Top 10 E-Pass Users",
    topUnauthorized: "Top Unauthorized Exits",
    teacherPassStats: "Passes by Teacher",
    total: "Total",
    percentage: "Percentage",
    count: "Count",
    viewReport: "View Report",
    noData: "No data available for the selected period."
  },
  ar: {
    login: "تسجيل الدخول",
    password: "كلمة المرور",
    demoMode: "وضع تجريبي",
    signIn: "تسجيل الدخول",
    loginDescription: "أدخل بيانات الاعتماد الخاصة بك للوصول إلى النظام.",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    welcome: "مرحباً بعودتك",
    selectRole: "اختر الدور للمحاكاة",
    forgotPassword: "نسيت كلمة المرور؟",
    resetPassword: "إعادة تعيين كلمة المرور",
    backToLogin: "العودة لتسجيل الدخول",
    resetLinkSent: "تم إرسال رابط إعادة التعيين! تحقق من بريدك الإلكتروني.",
    enterEmailToReset: "أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور.",
    sendLink: "إرسال رابط إعادة التعيين",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    totalStudents: "إجمالي الطلاب",
    onCampus: "حاضرون في المدرسة",
    absent: "غائب",
    late: "متأخر",
    askAi: "اسأل المحلل الذكي",
    aiThinking: "جاري تحليل البيانات...",
    recentActivity: "النشاط الأخير",
    activePasses: "التصاريح النشطة",
    createPass: "إنشاء تصريح",
    studentName: "اسم الطالب",
    status: "الحالة",
    actions: "الإجراءات",
    checkIn: "تسجيل دخول",
    checkOut: "تسجيل خروج",
    lateArrival: "وصول متأخر",
    earlyLeave: "انصراف مبكر",
    reason: "السبب",
    transportConflict: "تنبيه تعارض المواصلات!",
    busSchedule: "مجدول للحافلة",
    submit: "إرسال",
    analyzing: "جاري التحليل...",
    insight: "تحليل الذكاء الاصطناعي",
    switchLang: "English",
    management: "الإدارة",
    clinic: "العيادة",
    reception: "الاستقبال",
    users: "المستخدمين",
    students: "الطلاب",
    classes: "الفصول",
    upload: "رفع قائمة الطلاب",
    uploading: "جاري الرفع...",
    addUser: "إضافة مستخدم",
    addStudent: "إضافة طالب",
    role: "الدور",
    email: "البريد الإلكتروني",
    grade: "الصف",
    section: "القسم",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    studentNumber: "رقم الطالب",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    filterBy: "تصفية حسب",
    sortBy: "ترتيب حسب",
    searchPlaceholder: "بحث بالاسم أو الرقم...",
    clearFilters: "مسح التصفيات",
    downloadTemplate: "تحميل قالب إكسل",
    pickupBy: "تم الاستلام بواسطة",
    pickupId: "رقم هوية المستلم",
    otherReason: "تحديد السبب",
    selectReason: "اختر السبب",
    selectRelation: "اختر صلة القرابة",
    autoAttendance: "ملاحظة: سيتم وضع علامة 'انصراف مبكر' تلقائياً للطالب للفترات المتبقية.",
    destinations: "وجهات التصريح",
    addDestination: "إضافة وجهة",
    editDestination: "تعديل وجهة",
    duration: "المدة (دقيقة)",
    icon: "الأيقونة",
    color: "سمة اللون",
    labelEn: "الاسم (إنجليزي)",
    labelAr: "الاسم (عربي)",
    familyId: "رقم العائلة (ربط الإخوة)",
    siblings: "تم اكتشاف إخوة",
    // Attendance
    date: "التاريخ",
    period: "الحصة",
    weekend: "عطلة نهاية الأسبوع",
    noAttendance: "لا يوجد حضور مطلوب.",
    selectClass: "اختر الفصل",
    selectClassMsg: "يرجى اختيار الجنس، الصف، والقسم لعرض الطلاب.",
    noStudentsFound: "لم يتم العثور على طلاب مطابقين.",
    markAllAs: "تحديد الكل كـ...",
    apply: "تطبيق",
    clearAll: "مسح الكل",
    submitChanges: "حفظ التغييرات",
    attendanceSaved: "تم حفظ الحضور",
    confirmClear: "هل أنت متأكد أنك تريد مسح الحضور للطلاب الظاهرين؟",
    present: "حاضر",
    excused: "غائب بعذر",
    unexcused: "غائب بدون عذر",
    enterReason: "أدخل سبب الغياب",
    saveReason: "حفظ السبب",
    // E-Pass
    passes: "التصاريح",
    passActive: "تصريح نشط",
    passOverdue: "تصريح متأخر",
    endPass: "إنهاء التصريح",
    return: "عودة",
    outOfClass: "خروج بدون إذن",
    studentReturned: "عاد الطالب",
    dailyLimit: "تم الوصول للحد اليومي",
    allowAnyway: "السماح على أي حال",
    unauthorized: "غير مصرح",
    studentOutOfClass: "الطالب خارج الفصل.",
    selectGender: "اختر الجنس...",
    selectGrade: "اختر الصف...",
    selectSection: "اختر القسم...",
    activityMonitor: "مراقب النشاط",
    issuePass: "إصدار تصريح",
    totalActive: "إجمالي النشط",
    totalOverdue: "إجمالي المتأخر",
    destinationBreakdown: "تفاصيل التصاريح",
    activeStudentList: "قائمة الطلاب النشطين",
    timeElapsed: "الوقت المنقضي",
    where: "إلى أين",
    issuedBy: "أصدر بواسطة",
    // Reception
    readyToProcess: "جاهز للمعالجة",
    selectStudentMsg: "اختر طالباً من القائمة للبدء",
    confirmLate: "تأكيد الوصول المتأخر",
    confirmLateMsg: "سيتم تسجيل الطالب كـ \"متأخر\" للحصة الحالية.",
    guardianPickup: "استلام ولي الأمر",
    pleaseSpecify: "يرجى التحديد...",
    transport: "المواصلات",
    // Management
    timetable: "الجدول الزمني",
    timetableConfig: "إعداد الجدول الزمني",
    standard: "قياسي (الإثنين-الخميس)",
    friday: "الجمعة (يوم قصير)",
    sortChrono: "ترتيب زمنياً",
    startTime: "وقت البدء",
    endTime: "وقت الانتهاء",
    type: "النوع",
    addSlot: "إضافة فترة",
    saveSchedule: "حفظ الجدول",
    globalSettings: "إعدادات التصريح العامة",
    maxPasses: "الحد الأقصى للتصاريح للطالب / اليوم",
    updateLimit: "تحديث الحد",
    logout: "تسجيل خروج",
    generateId: "إصدار بطاقة هوية",
    printCard: "طباعة البطاقة",
    academicYear: "العام الدراسي 2024-2025",
    trackivaAcademy: "أكاديمية تراكيفا",
    allGrades: "كل الصفوف",
    allSections: "كل الأقسام",
    allGenders: "كل الأجناس",
    bus: "حافلة",
    car: "سيارة",
    walker: "ماشي",
    accessControl: "التحكم بالوصول",
    manageRoles: "إدارة صلاحيات الأدوار",
    module: "الوحدة",
    access: "الوصول",
    notifications: "الإشعارات",
    telegramSettings: "إعدادات تيليجرام",
    securityAlerts: "تنبيهات الأمن والتصاريح",
    receptionAlerts: "تنبيهات الاستقبال والانصراف المبكر",
    attendanceAlerts: "تنبيهات الحضور (الأخصائي الاجتماعي)",
    botToken: "رمز البوت",
    chatId: "معرف المحادثة",
    userChatId: "معرف محادثة تيليجرام للمستخدم",
    saveCredentials: "حفظ البيانات",
    watchlist: "طالب مستهدف / قائمة المراقبة",
    watchlistAlerts: "تنبيهات الطلاب المستهدفين",
    watchlistDesc: "إشعارات مخصصة للطلاب المحدد عليهم كـ 'مستهدف/قائمة مراقبة'.",
    notificationRules: "قواعد إشعارات التصاريح",
    enableNotificationsFor: "تفعيل الإشعارات لـ:",
    // Parent Notification
    parentNotifications: "إشعارات أولياء الأمور",
    parentNotificationsDesc: "تكوين تنبيهات تيليجرام لطلاب معينين لإخطار الآباء مباشرة.",
    searchStudent: "بحث عن طالب...",
    configureParentRules: "تكوين قواعد الوالدين",
    parentChatId: "معرف محادثة تيليجرام للوالد",
    selectEvents: "اختر الأحداث لإخطار الوالد",
    saveParentSettings: "حفظ إعدادات الوالد",
    // Attendance Rules
    attendanceRules: "قواعد الحضور",
    attendanceRulesDesc: "تكوين كيفية حساب حالة الحضور اليومي من سجلات الحصص.",
    absentThreshold: "حد يوم الغياب (حصص)",
    absentThresholdDesc: "عدد فترات الغياب غير المبرر لحساب يوم غياب كامل.",
    countAllExcused: "منطق الغياب بعذر",
    countAllExcusedDesc: "إذا تم تحديده، فسيتم احتساب الطالب الذي لديه جميع الفترات بعذر كـ 'غائب بعذر' لليوم.",
    attendanceAlertThresholds: "عتبات تنبيه الغياب (أيام)",
    attendanceAlertDesc: "اختر أيام الغياب المتراكم التي تؤدي إلى إرسال إشعار للأخصائي الاجتماعي.",
    saveRules: "حفظ القواعد",
    // User Management
    assignedClasses: "الفصول المعينة",
    assignClass: "تعيين فصل",
    selectGradeAndSection: "اختر الصف والقسم",
    addClass: "إضافة فصل",
    // Clinic
    incomingPatients: "الطلاب القادمون",
    noIncoming: "لا يوجد طلاب في الطريق حالياً.",
    admitPatient: "إدخال مريض",
    admitWalkIn: "إدخال طالب (بدون تصريح)",
    logVisit: "تسجيل زيارة",
    symptom: "العرض",
    diagnosis: "التشخيص / الملاحظات",
    treatment: "العلاج / الدواء",
    notes: "ملاحظات الممرضة",
    severity: "الشدة",
    outcome: "النتيجة",
    emergencyAlert: "تنبيه طوارئ",
    emergencyConfirm: "هل أنت متأكد أنك تريد إطلاق تنبيه الطوارئ؟",
    emergencyConfirmDesc: "سيقوم هذا بإخطار الإدارة والأمن فوراً. استخدمه فقط للحالات الحرجة.",
    visitLogged: "تم تسجيل الزيارة بنجاح",
    epidemicWarning: "تحذير وبائي",
    epidemicMsg: "تم اكتشاف عدد كبير من الحالات المماثلة مؤخراً:",
    todayVisits: "زيارات اليوم",
    sentHome: "تم إرساله للمنزل",
    medicalHistory: "السجل الطبي",
    low: "منخفض",
    medium: "متوسط",
    high: "مرتفع",
    emergency: "حرج",
    returnToClass: "عودة للفصل",
    sentHomeAction: "إرسال للمنزل",
    hospital: "تحويل للمستشفى",
    analytics: "التحليلات",
    commonComplaints: "الشكاوى الشائعة",
    visitTimeline: "الجدول الزمني للزيارات",
    confirmAction: "تأكيد",
    visitsByGrade: "الزيارات حسب الصف",
    visitsBySection: "الزيارات حسب القسم",
    visitsByGender: "الزيارات حسب الجنس",
    admitted: "تم القبول",
    discharged: "تم الخروج",
    studentReport: "تقرير الطالب",
    searchReportPlaceholder: "بحث عن اسم الطالب أو الرقم...",
    totalVisits: "إجمالي الزيارات",
    selectStudentForReport: "ابحث واختر طالباً لعرض تقريره الطبي.",
    noVisitsFound: "لم يتم العثور على زيارات لهذا الطالب.",
    // Reports
    reports: "التقارير",
    dailySummary: "الملخص اليومي",
    attendanceReport: "تقرير الحضور",
    clinicReport: "تقرير العيادة",
    epassReport: "تقرير التصاريح",
    receptionReport: "تقرير الاستقبال",
    student360: "ملف الطالب 360",
    exportReport: "تصدير التقرير",
    dateRange: "نطاق التاريخ",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    generate: "توليد",
    cycle: "الحلقة",
    cycle1: "الحلقة 1 (KG-G4)",
    cycle2: "الحلقة 2 (G5-G8)",
    cycle3: "الحلقة 3 (G9-G12)",
    absenteeList: "قائمة الغياب",
    absentBuckets: "تكرار الغياب",
    bucket1_2: "1-2 أيام",
    bucket3_5: "3-5 أيام",
    bucket6_9: "6-9 أيام",
    bucket10_14: "10-14 يوم",
    bucket15plus: "15+ يوم (علامة حمراء)",
    topComplaints: "أهم الشكاوى",
    topEPassUsers: "أكثر 10 طلاب استخداماً",
    topUnauthorized: "أكثر الخروج غير المصرح به",
    teacherPassStats: "التصاريح حسب المعلم",
    total: "الإجمالي",
    percentage: "النسبة",
    count: "العدد",
    viewReport: "عرض التقرير",
    noData: "لا توجد بيانات متاحة للفترة المحددة."
  }
};
