
import { 
  LayoutDashboard, 
  Users, 
  DoorOpen, 
  Ticket, 
  Stethoscope, 
  Settings,
  BarChart3
} from 'lucide-react';
import { UserRole, NavItem, Language, Student, EPassDestination, User } from './types';

export const ROLES_LIST = Object.values(UserRole);

export const NAV_ITEMS: NavItem[] = [
  {
    id: 'dashboard',
    label_en: 'Dashboard',
    label_ar: 'لوحة القيادة',
    icon: LayoutDashboard,
    allowedRoles: Object.values(UserRole)
  },
  {
    id: 'reports',
    label_en: 'Reports',
    label_ar: 'التقارير',
    icon: BarChart3,
    allowedRoles: [UserRole.ADMIN_SGL, UserRole.MIDDLE_LEADER]
  },
  {
    id: 'management',
    label_en: 'Management',
    label_ar: 'الإدارة',
    icon: Settings,
    allowedRoles: [UserRole.ADMIN_SGL]
  },
  {
    id: 'attendance',
    label_en: 'Attendance',
    label_ar: 'الحضور',
    icon: Users,
    allowedRoles: [UserRole.TEACHER, UserRole.ADMIN_SGL, UserRole.SUPERVISOR]
  },
  {
    id: 'reception',
    label_en: 'Reception',
    label_ar: 'الاستقبال',
    icon: DoorOpen,
    allowedRoles: [UserRole.ADMIN_SGL, UserRole.SUPERVISOR, UserRole.BUS_SUPERVISOR]
  },
  {
    id: 'epass',
    label_en: 'E-Pass',
    label_ar: 'التصريح الإلكتروني',
    icon: Ticket,
    allowedRoles: [UserRole.TEACHER, UserRole.SUPERVISOR, UserRole.MIDDLE_LEADER, UserRole.ADMIN_SGL]
  },
  {
    id: 'clinic',
    label_en: 'Clinic',
    label_ar: 'العيادة',
    icon: Stethoscope,
    allowedRoles: [UserRole.CLINIC_STAFF, UserRole.ADMIN_SGL]
  }
];

// Mock Data
export const MOCK_STUDENTS: Student[] = [
  {
    id: 'S001',
    studentNumber: '2024001',
    name_en: 'Ahmed Al-Falahi',
    name_ar: 'أحمد الفلاحي',
    gender: 'Male',
    grade: '10',
    section: 'A',
    transportMode: 'Bus',
    busRoute: 'R-101',
    familyId: 'FAM-001'
  },
  {
    id: 'S002',
    studentNumber: '2024002',
    name_en: 'Sarah Johnson',
    name_ar: 'سارة جونسون',
    gender: 'Female',
    grade: '11',
    section: 'B',
    transportMode: 'Car',
    familyId: 'FAM-002'
  },
  {
    id: 'S003',
    studentNumber: '2024003',
    name_en: 'Mohammad Ali',
    name_ar: 'محمد علي',
    gender: 'Male',
    grade: '10',
    section: 'A',
    transportMode: 'Walker',
    familyId: 'FAM-003',
    isWatchlisted: true
  },
  {
    id: 'S004',
    studentNumber: '2024004',
    name_en: 'Fatima Al-Sayed',
    name_ar: 'فاطمة السيد',
    gender: 'Female',
    grade: '10',
    section: 'A',
    transportMode: 'Bus',
    busRoute: 'R-102',
    familyId: 'FAM-001'
  },
  {
    id: 'S005',
    studentNumber: '2024005',
    name_en: 'John Doe',
    name_ar: 'جون دو',
    gender: 'Male',
    grade: '12',
    section: 'C',
    transportMode: 'Car',
  }
];

export const MOCK_USERS_SEED: User[] = [
  {
    id: 'U001',
    name: 'Admin User',
    email: 'admin@school.com',
    role: UserRole.ADMIN_SGL
  },
  {
    id: 'U002',
    name: 'Sarah Teacher',
    email: 'sarah@school.com',
    role: UserRole.TEACHER,
    assignedClasses: [{ grade: '10', section: 'A' }]
  },
  {
    id: 'U003',
    name: 'Security Guard',
    email: 'security@school.com',
    role: UserRole.SUPERVISOR
  },
  {
    id: 'U004',
    name: 'School Nurse',
    email: 'nurse@school.com',
    role: UserRole.CLINIC_STAFF
  },
  {
    id: 'U005',
    name: 'Mr. Social Worker',
    email: 'social@school.com',
    role: UserRole.SOCIAL_WORKER,
    assignedClasses: [{ grade: '10', section: 'A' }, { grade: '11', section: 'B' }]
  }
];

export const EARLY_LEAVE_REASONS = [
  "Medical Appointment",
  "Family Emergency",
  "Sickness",
  "Official Paperwork",
  "Travel",
  "Other"
];

export const PICKUP_RELATIONS = [
  "Father",
  "Mother",
  "Brother",
  "Sister",
  "Driver",
  "Maid",
  "Family Member",
  "Other"
];

export const CLINIC_SYMPTOMS = [
    "Headache",
    "Stomach Ache",
    "Fever",
    "Injury/Cut",
    "Nausea",
    "Dizziness",
    "Cough/Cold",
    "Allergic Reaction",
    "Other"
];

export const CLINIC_OUTCOMES = [
    "ReturnToClass",
    "SentHome"
];

export const DEFAULT_DESTINATIONS: EPassDestination[] = [
    { id: 'Restroom', label_en: 'Restroom', label_ar: 'دورة مياه', iconName: 'Armchair', colorTheme: 'blue', maxDuration: 5 },
    { id: 'Clinic', label_en: 'Clinic', label_ar: 'العيادة', iconName: 'Stethoscope', colorTheme: 'red', maxDuration: 15 },
    { id: 'Library', label_en: 'Library', label_ar: 'المكتبة', iconName: 'Library', colorTheme: 'yellow', maxDuration: 20 },
    { id: 'Office', label_en: 'Admin Office', label_ar: 'الإدارة', iconName: 'Briefcase', colorTheme: 'slate', maxDuration: 10 },
];

export const AVAILABLE_ICONS = [
    'Armchair', 'Stethoscope', 'Library', 'Briefcase', 'Coffee', 'Gamepad2', 'Music', 'Dumbbell', 'Beaker', 'BookOpen', 'Users'
];

export const COLOR_THEMES = [
    { name: 'blue', class: 'bg-blue-50 text-blue-600 hover:bg-blue-100' },
    { name: 'red', class: 'bg-red-50 text-red-600 hover:bg-red-100' },
    { name: 'yellow', class: 'bg-yellow-50 text-yellow-600 hover:bg-yellow-100' },
    { name: 'green', class: 'bg-green-50 text-green-600 hover:bg-green-100' },
    { name: 'purple', class: 'bg-purple-50 text-purple-600 hover:bg-purple-100' },
    { name: 'orange', class: 'bg-orange-50 text-orange-600 hover:bg-orange-100' },
    { name: 'slate', class: 'bg-slate-50 text-slate-600 hover:bg-slate-100' },
];


export const TRANSLATIONS = {
  en: {
    login: "Login",
    password: "Password",
    demoMode: "Demo Mode",
    signIn: "Sign In",
    loginDescription: "Enter your credentials to access the system.",
    invalidCredentials: "Invalid email or password.",
    welcome: "Welcome back",
    selectRole: "Select Role to Simulate",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    backToLogin: "Back to Login",
    resetLinkSent: "Reset link sent! Check your email.",
    enterEmailToReset: "Enter your email to receive a password reset link.",
    sendLink: "Send Reset Link",
    totalStudents: "Total Students",
    onCampus: "Present on Campus",
    absent: "Absent",
    late: "Late",
    askAi: "Ask AI Analyst",
    aiThinking: "Analyzing Data...",
    recentActivity: "Recent Activity",
    activePasses: "Active E-Passes",
    createPass: "Create E-Pass",
    studentName: "Student Name",
    status: "Status",
    actions: "Actions",
    checkIn: "Check In",
    checkOut: "Check Out",
    lateArrival: "Late Arrival",
    earlyLeave: "Early Leave",
    reason: "Reason",
    transportConflict: "Transport Conflict Alert!",
    busSchedule: "Scheduled for Bus",
    submit: "Submit",
    analyzing: "Analyzing...",
    insight: "AI Insight",
    switchLang: "العربية",
    management: "Management",
    clinic: "Clinic",
    reception: "Reception",
    users: "Users",
    students: "Students",
    classes: "Classes",
    upload: "Upload Students List",
    uploading: "Uploading...",
    addUser: "Add User",
    addStudent: "Add Student",
    role: "Role",
    email: "Email",
    grade: "Grade",
    section: "Section",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    studentNumber: "Student No.",
    gender: "Gender",
    male: "Male",
    female: "Female",
    filterBy: "Filter By",
    sortBy: "Sort By",
    searchPlaceholder: "Search by Name or Number...",
    clearFilters: "Clear Filters",
    downloadTemplate: "Download Excel Template",
    pickupBy: "Picked Up By",
    pickupId: "Picker ID Number",
    otherReason: "Specify Reason",
    selectReason: "Select Reason",
    selectRelation: "Select Relation",
    autoAttendance: "Note: Student will be automatically marked as Early Leave (EL) for remaining periods.",
    destinations: "E-Pass Destinations",
    addDestination: "Add Destination",
    editDestination: "Edit Destination",
    duration: "Duration (mins)",
    icon: "Icon",
    color: "Color Theme",
    labelEn: "Label (English)",
    labelAr: "Label (Arabic)",
    familyId: "Family ID (Sibling Link)",
    siblings: "Siblings Detected",
    // Attendance
    date: "Date",
    period: "Period",
    weekend: "Weekend",
    noAttendance: "No attendance required.",
    selectClass: "Select Class",
    selectClassMsg: "Please select Gender, Grade, and Section to view students.",
    noStudentsFound: "No students found matching these filters.",
    markAllAs: "Mark All As...",
    apply: "Apply",
    clearAll: "Clear All",
    submitChanges: "Submit Changes",
    attendanceSaved: "Attendance Saved",
    confirmClear: "Are you sure you want to clear attendance for visible students?",
    present: "Present",
    excused: "Excused Absent",
    unexcused: "Unexcused",
    enterReason: "Enter Reason for Absence",
    saveReason: "Save Reason",
    // E-Pass
    passes: "Passes",
    passActive: "Pass Active",
    passOverdue: "Pass Overdue",
    endPass: "End Pass",
    return: "Return",
    outOfClass: "OUT WITHOUT PERMISSION",
    studentReturned: "Student Returned",
    dailyLimit: "Daily Limit Reached",
    allowAnyway: "Allow Anyway",
    unauthorized: "UNAUTHORIZED",
    studentOutOfClass: "Student is out of class.",
    selectGender: "Select Gender...",
    selectGrade: "Select Grade...",
    selectSection: "Select Section...",
    activityMonitor: "Activity Monitor",
    issuePass: "Issue Pass",
    totalActive: "Total Active",
    totalOverdue: "Total Overdue",
    destinationBreakdown: "Passes Breakdown",
    activeStudentList: "Active Students List",
    timeElapsed: "Time Elapsed",
    where: "Where",
    issuedBy: "Issued By",
    // Reception
    readyToProcess: "Ready to Process",
    selectStudentMsg: "Select a student from the list to begin",
    confirmLate: "Confirm Late Arrival",
    confirmLateMsg: "Student will be marked as \"Late\" for the current period.",
    guardianPickup: "Guardian / Pickup",
    pleaseSpecify: "Please specify...",
    transport: "Transport",
    // Management
    timetable: "Timetable",
    timetableConfig: "Timetable Configuration",
    standard: "Standard (Mon-Thu)",
    friday: "Friday (Short Day)",
    sortChrono: "Sort Chronologically",
    startTime: "Start Time",
    endTime: "End Time",
    type: "Type",
    addSlot: "Add Slot",
    saveSchedule: "Save Schedule Changes",
    globalSettings: "Global E-Pass Settings",
    maxPasses: "Max Passes Per Student / Day",
    updateLimit: "Update Limit",
    logout: "Logout",
    generateId: "Generate ID Card",
    printCard: "Print Card",
    academicYear: "Academic Year 2024-2025",
    trackivaAcademy: "Trackiva Academy",
    allGrades: "All Grades",
    allSections: "All Sections",
    allGenders: "All Genders",
    bus: "Bus",
    car: "Car",
    walker: "Walker",
    accessControl: "Access Control",
    manageRoles: "Manage Role Permissions",
    module: "Module",
    access: "Access",
    notifications: "Notifications",
    telegramSettings: "Telegram Configuration",
    securityAlerts: "Security & E-Pass Alerts",
    receptionAlerts: "Reception & Early Leave Alerts",
    attendanceAlerts: "Attendance Alerts (Social Worker)",
    botToken: "Bot Token",
    chatId: "Chat ID",
    userChatId: "User Telegram Chat ID",
    saveCredentials: "Save Credentials",
    watchlist: "Targeted / Watchlist Student",
    watchlistAlerts: "Targeted Student Alerts",
    watchlistDesc: "Dedicated notifications for students marked as 'Targeted/Watchlisted'.",
    notificationRules: "E-Pass Notification Rules",
    enableNotificationsFor: "Enable Notifications For:",
    // Parent Notification
    parentNotifications: "Parent Notifications",
    parentNotificationsDesc: "Configure Telegram alerts for specific students to notify parents directly.",
    searchStudent: "Search Student...",
    configureParentRules: "Configure Parent Rules",
    parentChatId: "Parent Telegram Chat ID",
    selectEvents: "Select Events to Notify Parent",
    saveParentSettings: "Save Parent Settings",
    // Attendance Rules
    attendanceRules: "Attendance Rules",
    attendanceRulesDesc: "Configure how daily attendance status is calculated from period records.",
    absentThreshold: "Absent Day Threshold (Periods)",
    absentThresholdDesc: "Number of unexcused absences (periods) to count as a full Absent Day.",
    countAllExcused: "Excused Absence Logic",
    countAllExcusedDesc: "If checked, a student with ALL periods marked 'Excused' will be counted as 'Excused Absent' for the day.",
    attendanceAlertThresholds: "Absence Alert Thresholds (Days)",
    attendanceAlertDesc: "Select which days of accumulated absence trigger a notification to the assigned Social Worker.",
    saveRules: "Save Rules",
    // User Management
    assignedClasses: "Assigned Classes",
    assignClass: "Assign Class",
    selectGradeAndSection: "Select Grade and Section",
    addClass: "Add Class",
    // Clinic
    incomingPatients: "Incoming Students",
    noIncoming: "No students currently en route.",
    admitPatient: "Admit Student",
    admitWalkIn: "Admit Walk-in Student",
    logVisit: "Log Visit",
    symptom: "Symptom",
    diagnosis: "Diagnosis / Observations",
    treatment: "Treatment / Medicine",
    notes: "Nurse Notes",
    severity: "Severity",
    outcome: "Outcome",
    emergencyAlert: "EMERGENCY ALERT",
    emergencyConfirm: "Are you sure you want to trigger the Emergency Alert?",
    emergencyConfirmDesc: "This will instantly notify administration and security personnel. Only use for critical situations.",
    visitLogged: "Visit Logged Successfully",
    epidemicWarning: "Epidemic Warning",
    epidemicMsg: "High number of similar cases detected recently:",
    todayVisits: "Today's Visits",
    sentHome: "Sent Home",
    medicalHistory: "Medical History",
    low: "Low",
    medium: "Medium",
    high: "High",
    emergency: "Critical",
    returnToClass: "Return to Class",
    sentHomeAction: "Send Home",
    hospital: "Refer to Hospital",
    analytics: "Analytics",
    commonComplaints: "Common Complaints",
    visitTimeline: "Visit Timeline",
    confirmAction: "Confirm",
    visitsByGrade: "Visits by Grade",
    visitsBySection: "Visits by Section",
    visitsByGender: "Visits by Gender",
    admitted: "Admitted",
    discharged: "Discharged",
    studentReport: "Student Report",
    searchReportPlaceholder: "Search Student Name or ID...",
    totalVisits: "Total Visits",
    selectStudentForReport: "Search and select a student to view their medical report.",
    noVisitsFound: "No visits found for this student.",
    // Reports
    reports: "Reports",
    dailySummary: "Daily Summary",
    attendanceReport: "Attendance Report",
    clinicReport: "Clinic Report",
    epassReport: "E-Pass Report",
    receptionReport: "Reception Report",
    student360: "Student 360",
    exportReport: "Export Report",
    dateRange: "Date Range",
    startDate: "Start Date",
    endDate: "End Date",
    generate: "Generate",
    cycle: "Cycle",
    cycle1: "Cycle 1 (KG-G4)",
    cycle2: "Cycle 2 (G5-G8)",
    cycle3: "Cycle 3 (G9-G12)",
    absenteeList: "Absentee List",
    absentBuckets: "Absence Frequency",
    bucket1_2: "1-2 Days",
    bucket3_5: "3-5 Days",
    bucket6_9: "6-9 Days",
    bucket10_14: "10-14 Days",
    bucket15plus: "15+ Days (Red Flag)",
    topComplaints: "Common Complaints",
    topEPassUsers: "Top 10 E-Pass Users",
    topUnauthorized: "Top Unauthorized Exits",
    teacherPassStats: "Passes by Teacher",
    total: "Total",
    percentage: "Percentage",
    count: "Count",
    viewReport: "View Report",
    noData: "No data available for the selected period."
  },
  ar: {
    login: "تسجيل الدخول",
    password: "كلمة المرور",
    demoMode: "وضع التجربة",
    signIn: "دخول",
    loginDescription: "أدخل بيانات الاعتماد الخاصة بك للوصول إلى النظام.",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    welcome: "مرحباً بعودتك",
    selectRole: "اختر دوراً للمحاكاة",
    forgotPassword: "نسيت كلمة المرور؟",
    resetPassword: "إعادة تعيين كلمة المرور",
    backToLogin: "العودة لتسجيل الدخول",
    resetLinkSent: "تم إرسال رابط إعادة التعيين! تفقد بريدك الإلكتروني.",
    enterEmailToReset: "أدخل بريدك الإلكتروني لاستلام رابط إعادة تعيين كلمة المرور.",
    sendLink: "إرسال الرابط",
    totalStudents: "إجمالي الطلاب",
    onCampus: "في الحرم المدرسي",
    absent: "غائب",
    late: "تأخير",
    askAi: "اسأل المحلل الذكي",
    aiThinking: "جاري تحليل البيانات...",
    recentActivity: "النشاط الأخير",
    activePasses: "التصاريح النشطة",
    createPass: "إنشاء تصريح",
    studentName: "اسم الطالب",
    status: "الحالة",
    actions: "إجراءات",
    checkIn: "تسجيل دخول",
    checkOut: "تسجيل خروج",
    lateArrival: "وصول متأخر",
    earlyLeave: "انصراف مبكر",
    reason: "السبب",
    transportConflict: "تنبيه تعارض المواصلات!",
    busSchedule: "مجدول للحافلة",
    submit: "إرسال",
    analyzing: "جاري التحليل...",
    insight: "رؤية ذكية",
    switchLang: "English",
    management: "الإدارة",
    clinic: "العيادة",
    reception: "الاستقبال",
    users: "المستخدمين",
    students: "الطلاب",
    classes: "الفصول",
    upload: "رفع قائمة الطلاب",
    uploading: "جاري الرفع...",
    addUser: "إضافة مستخدم",
    addStudent: "إضافة طالب",
    role: "الدور",
    email: "البريد الإلكتروني",
    grade: "الصف",
    section: "الشعبة",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    studentNumber: "رقم الطالب",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    filterBy: "تصفية حسب",
    sortBy: "فرز حسب",
    searchPlaceholder: "بحث بالاسم أو الرقم...",
    clearFilters: "مسح المرشحات",
    downloadTemplate: "تحميل قالب إكسل",
    pickupBy: "تم الاستلام بواسطة",
    pickupId: "رقم هوية المستلم",
    otherReason: "حدد السبب",
    selectReason: "اختر السبب",
    selectRelation: "اختر صلة القرابة",
    autoAttendance: "ملاحظة: سيتم تسجيل الطالب تلقائياً كـ انصراف مبكر (EL) للحصص المتبقية.",
    destinations: "وجهات التصريح",
    addDestination: "إضافة وجهة",
    editDestination: "تعديل الوجهة",
    duration: "المدة (دقائق)",
    icon: "الأيقونة",
    color: "اللون",
    labelEn: "الاسم (إنجليزي)",
    labelAr: "الاسم (عربي)",
    familyId: "رقم العائلة (ربط الأخوة)",
    siblings: "الأخوة المكتشفون",
    // Attendance
    date: "التاريخ",
    period: "الحصة",
    weekend: "عطلة نهاية الأسبوع",
    noAttendance: "لا يوجد حضور مطلوب.",
    selectClass: "اختر الفصل",
    selectClassMsg: "يرجى اختيار الجنس، الصف، والشعبة لعرض الطلاب.",
    noStudentsFound: "لم يتم العثور على طلاب مطابقين.",
    markAllAs: "تحديد الكل كـ...",
    apply: "تطبيق",
    clearAll: "مسح الكل",
    submitChanges: "إرسال التغييرات",
    attendanceSaved: "تم حفظ الحضور",
    confirmClear: "هل أنت متأكد من مسح الحضور للطلاب الظاهرين؟",
    present: "حاضر",
    excused: "غياب بعذر",
    unexcused: "بدون عذر",
    enterReason: "أدخل سبب الغياب",
    saveReason: "حفظ السبب",
    // E-Pass
    passes: "التصاريح",
    passActive: "تصريح نشط",
    passOverdue: "تصريح متأخر",
    endPass: "إنهاء التصريح",
    return: "عودة",
    outOfClass: "خروج بدون إذن",
    studentReturned: "عاد الطالب",
    dailyLimit: "وصل للحد اليومي",
    allowAnyway: "السماح وتجاوز الحد",
    unauthorized: "غير مصرح",
    studentOutOfClass: "الطالب خارج الفصل.",
    selectGender: "اختر الجنس...",
    selectGrade: "اختر الصف...",
    selectSection: "اختر الشعبة...",
    activityMonitor: "مراقب النشاط",
    issuePass: "إصدار تصريح",
    totalActive: "إجمالي النشطة",
    totalOverdue: "إجمالي المتأخرة",
    destinationBreakdown: "تفاصيل التصاريح",
    activeStudentList: "قائمة الطلاب النشطين",
    timeElapsed: "المدة المنقضية",
    where: "الوجهة",
    issuedBy: "صدر بواسطة",
    // Reception
    readyToProcess: "جاهز للمعالجة",
    selectStudentMsg: "اختر طالباً من القائمة للبدء",
    confirmLate: "تأكيد التأخير",
    confirmLateMsg: "سيتم تسجيل الطالب كـ \"متأخر\" للحصة الحالية.",
    guardianPickup: "ولي الأمر / المستلم",
    pleaseSpecify: "يرجى التحديد...",
    transport: "المواصلات",
    // Management
    timetable: "الجدول الدراسي",
    timetableConfig: "إعدادات الجدول",
    standard: "قياسي (الاثنين-الخميس)",
    friday: "الجمعة (يوم قصير)",
    sortChrono: "فرز زمني",
    startTime: "وقت البدء",
    endTime: "وقت الانتهاء",
    type: "النوع",
    addSlot: "إضافة فترة",
    saveSchedule: "حفظ التغييرات",
    globalSettings: "إعدادات التصريح",
    maxPasses: "الحد الأقصى للتصاريح / يوم",
    updateLimit: "تحديث الحد",
    logout: "تسجيل خروج",
    generateId: "إنشاء بطاقة هوية",
    printCard: "طباعة البطاقة",
    academicYear: "العام الدراسي 2024-2025",
    trackivaAcademy: "أكاديمية تراكيفا",
    allGrades: "كل الصفوف",
    allSections: "كل الشعب",
    allGenders: "كل الأجناس",
    bus: "حافلة",
    car: "سيارة",
    walker: "مشي",
    accessControl: "التحكم في الوصول",
    manageRoles: "إدارة صلاحيات الأدوار",
    module: "الوحدة",
    access: "الوصول",
    notifications: "الإشعارات",
    telegramSettings: "إعدادات تيليجرام",
    securityAlerts: "تنبيهات الأمن والتصاريح",
    receptionAlerts: "تنبيهات الاستقبال والمغادرة",
    attendanceAlerts: "تنبيهات الحضور (الأخصائي الاجتماعي)",
    botToken: "رمز البوت (Bot Token)",
    chatId: "معرف المحادثة (Chat ID)",
    userChatId: "معرف محادثة المستخدم (Chat ID)",
    saveCredentials: "حفظ البيانات",
    watchlist: "طالب مستهدف / قائمة المراقبة",
    watchlistAlerts: "تنبيهات الطلاب المستهدفين",
    watchlistDesc: "إشعارات مخصصة للطلاب المحدد لهم 'مراقبة/استهداف'.",
    notificationRules: "قواعد إشعارات التصريح الإلكتروني",
    enableNotificationsFor: "تفعيل الإشعارات لـ:",
    // Parent Notifications
    parentNotifications: "تنبيهات أولياء الأمور",
    parentNotificationsDesc: "تكوين تنبيهات تيليجرام لطلاب محددين لإخطار أولياء الأمور مباشرة.",
    searchStudent: "بحث عن طالب...",
    configureParentRules: "إعدادات تنبيهات الوالدين",
    parentChatId: "معرف محادثة الوالدين (Chat ID)",
    selectEvents: "اختر الأحداث لتنبيه الوالدين",
    saveParentSettings: "حفظ إعدادات الوالدين",
    // Attendance Rules
    attendanceRules: "قواعد الحضور",
    attendanceRulesDesc: "تكوين كيفية حساب حالة الحضور اليومي من سجلات الحصص.",
    absentThreshold: "حد الغياب اليومي (عدد الحصص)",
    absentThresholdDesc: "عدد الحصص (بدون عذر) التي تُحسب كيوم غياب كامل.",
    countAllExcused: "منطق الغياب بعذر",
    countAllExcusedDesc: "إذا تم تحديده، سيتم احتساب الطالب الذي لديه عذر في جميع الحصص كـ 'غائب بعذر' لليوم.",
    attendanceAlertThresholds: "عتبات تنبيه الغياب (أيام)",
    attendanceAlertDesc: "حدد أيام الغياب التراكمي التي تؤدي إلى إرسال إشعار للأخصائي الاجتماعي المسؤول.",
    saveRules: "حفظ القواعد",
    // User Management
    assignedClasses: "الفصول المسندة",
    assignClass: "إسناد فصل",
    selectGradeAndSection: "اختر الصف والشعبة",
    addClass: "إضافة فصل",
    // Clinic
    incomingPatients: "الطلاب القادمون",
    noIncoming: "لا يوجد طلاب قادمون حالياً.",
    admitPatient: "استقبال الطالب",
    admitWalkIn: "استقبال طالب (بدون تصريح)",
    logVisit: "تسجيل زيارة",
    symptom: "العرض",
    diagnosis: "التشخيص / الملاحظات",
    treatment: "العلاج / الدواء",
    notes: "ملاحظات الممرض/ة",
    severity: "الحدة",
    outcome: "النتيجة",
    emergencyAlert: "تنبيه طوارئ",
    emergencyConfirm: "هل أنت متأكد من تفعيل تنبيه الطوارئ؟",
    emergencyConfirmDesc: "سيتم إشعار الإدارة وفريق الأمن فوراً. استخدمه فقط في الحالات الحرجة.",
    visitLogged: "تم تسجيل الزيارة بنجاح",
    epidemicWarning: "تحذير وبائي",
    epidemicMsg: "تم رصد عدد كبير من الحالات المتشابهة مؤخراً:",
    todayVisits: "زيارات اليوم",
    sentHome: "تم إرسالهم للمنزل",
    medicalHistory: "السجل الطبي",
    low: "منخفض",
    medium: "متوسط",
    high: "عالي",
    emergency: "حرج",
    returnToClass: "عودة للفصل",
    sentHomeAction: "إرسال للمنزل",
    hospital: "تحويل للمستشفى",
    analytics: "التحليلات",
    commonComplaints: "الشكاوى الشائعة",
    visitTimeline: "الجدول الزمني للزيارات",
    confirmAction: "تأكيد",
    visitsByGrade: "الزيارات حسب الصف",
    visitsBySection: "الزيارات حسب الشعبة",
    visitsByGender: "الزيارات حسب الجنس",
    admitted: "دخول",
    discharged: "خروج",
    studentReport: "تقرير الطالب",
    searchReportPlaceholder: "بحث عن طالب بالاسم أو الرقم...",
    totalVisits: "إجمالي الزيارات",
    selectStudentForReport: "ابحث واختر طالباً لعرض سجله الطبي.",
    noVisitsFound: "لا توجد زيارات مسجلة لهذا الطالب.",
    // Reports
    reports: "التقارير",
    dailySummary: "الملخص اليومي",
    attendanceReport: "تقرير الحضور",
    clinicReport: "تقرير العيادة",
    epassReport: "تقرير التصاريح",
    receptionReport: "تقرير الاستقبال",
    student360: "تقرير الطالب الشامل",
    exportReport: "تصدير التقرير",
    dateRange: "النطاق الزمني",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    generate: "توليد",
    cycle: "الحلقة",
    cycle1: "الحلقة 1 (الروضة-4)",
    cycle2: "الحلقة 2 (5-8)",
    cycle3: "الحلقة 3 (9-12)",
    absenteeList: "قائمة الغياب",
    absentBuckets: "تكرار الغياب",
    bucket1_2: "1-2 أيام",
    bucket3_5: "3-5 أيام",
    bucket6_9: "6-9 أيام",
    bucket10_14: "10-14 يوم",
    bucket15plus: "15+ يوم (علامة حمراء)",
    topComplaints: "أهم الشكاوى",
    topEPassUsers: "أكثر 10 طلاب استخداماً",
    topUnauthorized: "أكثر الخروج غير المصرح به",
    teacherPassStats: "التصاريح حسب المعلم",
    total: "الإجمالي",
    percentage: "النسبة",
    count: "العدد",
    viewReport: "عرض التقرير",
    noData: "لا توجد بيانات متاحة للفترة المحددة."
  }
};
